apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spring-petclinic
  namespace: openshift-gitops
spec:
  destination:
    namespace: devsecops-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/dev
    repoURL: https://github.com/basavaraju-g/spring-petclinic-config
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
