apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:39a7ad60feade9d7d8d1f19eb93dc4ef095a2501cde68aa86ee76237861677aa
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: image-registry.openshift-image-registry.svc:5000/cicd/spring-petclinic
