apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:cd841248e63cde77a7bfed5da7cbf4c1b5e38bc1c201977265c18f88ed803023
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/bgirriam/spring-petclinic
