apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:ee423521dc4531cc108893eddfb0ab3169e56d346fbd5f7c13b0487aa9a06d67
  name: quay.io/siamaksade/spring-petclinic:latest
  newName: quay.io/bgirriam/spring-petclinic
